### PR TITLE
AlmaLinux/build-system#272: Add permanent saving a BW session and wor…

### LINKED ISSUE #272: Add permanent saving a BW session and working with API key to the BW wrapper
https://github.com/AlmaLinux/py-bitwarden-wrapper

1. Add saving a BW session, e.g. to `~/.bashrc`. It will be useful in an Ansible scenario
2. Add working with API key. It's a single way to login if your account has enabled 2fa

### PR DESCRIPTION
**Pull request by soksanichenko**
…king with API key to the BW wrapper

### CODE REVIEW

**Comment by codyro** [comment]
Is the intention to use this for secret management moving forward? If so, we have an [Infisical](https://github.com/Infisical/infisical) license and test instance up, which would be favored over BitWarden/VaultWarden (I think?). 

CC @jonathanspw

**Comment by Korulag** [comment]
@codyro I'm not sure about yet another system for storing credentials... We already use Vaultwarden to store production secrets there, this wrapper was already proven working in other system. Do you want to fully replace Vaultwarden by this Infisical?

**Comment by codyro** [comment]
While VaultWarden can store secrets, it's more of a password manager than a secret management system, as you've likely deduced from how it differs from traditional systems like Hashicorp Vault, etc. 

I believe the intention was to use Infiscal for secret management (CI/CD, etc.) while using VaultWarden for password management for AlmaLinux (SIGs, etc.). 

@jonathanspw, do you have any input and or thoughts?

**EDIT** One additional thought: using a "proper" secret manager will allow for better auditing & restricting/ACLing of secrets, which is important to consider.

**Comment by jonathanspw** [comment]
> I believe the intention was to use Infiscal for secret management (CI/CD, etc.) while using VaultWarden for password management for AlmaLinux (SIGs, etc.).

This was the exact intention.

Is there a benefit to using VW over a proper secrets manager?  The "secrets manager" aspect of Bitwarden don't seem to exist in Vaultwarden.

**Comment by jonathanspw** [comment]
Is anyone opposed to hashicorp vault?

**Comment by iseletsk** [comment]
Can we use some cloud solution instead? Otherwise we need to HSM to make it right, and it is a pain to host, manage, provide HA.

**Comment by jonathanspw** [comment]
> Can we use some cloud solution instead? Otherwise we need to HSM to make it right, and it is a pain to host, manage, provide HA.

I'd rather avoid the vendor-lock of a cloud solution.

Why do we need HSM for basic secrets management?

**Comment by iseletsk** [comment]
Think of it as cost/benefit. With cloud, Your cost is is vendor lock in. The benefit - 10x smaller cost, less time to manage, compliance out of the box, etc...

Why you need HSM - if you plan to pass any type of audit with that secret management, you will need HSM (best practices).
Otherwise - just think how great of a target it is, if you can get in, and get ALL the secrets in one go? HSM helps with that.

**Comment by jonathanspw** [comment]
Hashicorp Vault is built to rival cloud offerings and the cost would be trivial, or rather, free.  It's very easy to host, I have an install up right now that I was building out for prod.

Unlike vaultwarden, for a proper secrets system it could be locked down our VPN which significantly limits the attack vectors.

I'm not vehemently opposed to cloud solutions (AWS I guess) but I think self-hosted might be the best solution long term.

**Review by zklevsha — APPROVED** [review]

**Comment by Korulag** [comment]
New build system does not have that much secrets, but we want the ability to store passwords from GPG keys we use for packages signing, so we need the most secure solution. The whole reason of using Vaultwarden is that we have an experience with it from CL build system. Hashicorp Vault also sounds fine, but we'll need to implement additional code to work with it

**Comment by jonathanspw** [comment]
> New build system does not have that much secrets, but we want the ability to store passwords from GPG keys we use for packages signing, so we need the most secure solution. The whole reason of using Vaultwarden is that we have an experience with it from CL build system. Hashicorp Vault also sounds fine, but we'll need to implement additional code to work with it

I've been spending some time looking into AWS ASM and giving it a fair shake though I'm not quite done digging into it and comparing it to Vault.

**Comment by jonathanspw** [comment]
AWS Secrets and Hashicorp Vault can mostly do the same stuff.

The biggest difference I've found that will impact us is the authentication component.  It will be much easier to manage permissions long-term with Vault given that it can use our direct AlmaLinux Accounts groups without the AWS IAM layer in the middle which will add complexity.

@Korulag both systems have an abundance of client libraries available.  I assume from an implementation perspective they'll be about the same amount of work?

**Comment by Korulag** [comment]
@jonathanspw yes, from the implementation perspective it's pretty much the same amount. However, if we want to use Vault, we just need to create a separate tickets for that (it needs to be added to separate repositories). As for this one - I think we can merge this PR, it may be valuable for interaction with Bitwarden/Vaultwarden anyway

**Review by Korulag — APPROVED** [review]

**Pull request merged**
